name: drugshield
repository: https://github.com/drugshield/drugshield

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

  version:
    branch: main

scripts:
  analyze:
    run: melos exec -- "dart analyze --fatal-infos"
    description: Run `dart analyze` in all packages.

  test:
    run: melos exec -- "flutter test"
    packageFilters:
      dirExists: test
    description: Run `flutter test` in all packages with tests.

  gen:ffigen:
    run: melos exec -- "dart run ffigen"
    packageFilters:
      fileExists: ffigen.yaml
    description: Generate FFI bindings for native packages.

  gen:proto:
    run: |
      protoc --dart_out=grpc:packages/proto/lib/generated \
             --go_out=backend/internal/handler \
             --go-grpc_out=backend/internal/handler \
             -Ipackages/proto \
             packages/proto/*.proto
    description: Generate Dart and Go code from Protobuf definitions.

  clean:
    run: melos exec -- "flutter clean"
    description: Clean all packages.
